## 세팅

In [ ]:
import pandas as pd
import numpy as np
import os

## 데이터셋

In [ ]:
# 데이터셋 불러오기
naver_df = pd.read_csv('C:\\Users\\jaewo\\Downloads\\naver_review_name.csv', index_col=0)

In [ ]:
naver_df.head(10)

address                road_address  near_station  \
search_name                                                        
버블베어               방화동  서울 강서구 금낭화로 167 방화8단지개화아파트          5방화역   
커피빈 낙성대역점          봉천동      서울 관악구 남부순환로 1909 1,2층         2낙성대역   
노란꼬무줄 선릉본점         대치동   서울 강남구 선릉로 424 1층5호 노란꼬무줄      2수인분당선릉역   
커피랩                서교동           서울 마포구 와우산로29길 14  2공항경의중앙홍대입구역   
커핀그루나루 신천점         잠실동            서울 송파구 올림픽로12길 8        2잠실새내역   
빌리엔젤마리오아울렛         가산동      서울 금천구 디지털로9길 23 3관 6층    17가산디지털단지역   
할리스 남부터미널점         서초동        서울 서초구 서초중앙로 52 영진빌딩       3남부터미널역   
홈스테드 타워팰리스점        도곡동    서울 강남구 언주로30길 39 린스퀘어 1층      3수인분당도곡역   
이디야커피 신길역점         신길동    서울 영등포구 영등포로 353 엔씨티오피스텔         15신길역   
엔제리너스 여의도리버타워점    여의도동                         NaN           NaN   

                station_distance  total_review  "커피가 맛있어요"  "친절해요"  \
search_name                                                          
버블베어                       427.0            18         7.0     5.0   
커피빈 낙성대역점                  119.0           284         7.0    56.0   
노란꼬무줄 선릉본점                 157.0           134        40.0    14.0   
커피랩                        324.0           100        76.0    23.0   
커핀그루나루 신천점                 228.0           140        64.0    14.0   
빌리엔젤마리오아울렛                 200.0           207        74.0    21.0   
할리스 남부터미널점                 156.0           204         7.0    41.0   
홈스테드 타워팰리스점                333.0           119        73.0    20.0   
이디야커피 신길역점                 203.0           172         2.0    32.0   
엔제리너스 여의도리버타워점               NaN           637         1.0     0.0   

                "음료가 맛있어요"  "디저트가 맛있어요"  "매장이 청결해요"  ...  "집중하기 좋아요"  \
search_name                                          ...               
버블베어                   5.0          6.0         5.0  ...         0.0   
커피빈 낙성대역점             74.0         37.0        40.0  ...        48.0   
노란꼬무줄 선릉본점            61.0         39.0         2.0  ...         0.0   
커피랩                   13.0          9.0         8.0  ...        10.0   
커핀그루나루 신천점            31.0         13.0        15.0  ...         7.0   
빌리엔젤마리오아울렛            53.0         77.0        30.0  ...        23.0   
할리스 남부터미널점            47.0         54.0        31.0  ...        14.0   
홈스테드 타워팰리스점           30.0         28.0        10.0  ...         5.0   
이디야커피 신길역점            27.0         14.0        22.0  ...         6.0   
엔제리너스 여의도리버타워점        96.0         95.0        85.0  ...        29.0   

                "인테리어가 멋져요"  "좌석이 편해요"  "화장실이 깨끗해요"  "특별한 메뉴가 있어요"  \
search_name                                                          
버블베어                    0.0        1.0          2.0            2.0   
커피빈 낙성대역점               8.0       33.0          2.0            2.0   
노란꼬무줄 선릉본점              1.0        0.0          0.0           21.0   
커피랩                    19.0        2.0          6.0           10.0   
커핀그루나루 신천점              2.0       15.0          5.0            5.0   
빌리엔젤마리오아울렛             11.0        0.0          6.0           13.0   
할리스 남부터미널점             31.0       18.0          2.0           13.0   
홈스테드 타워팰리스점             4.0        5.0          0.0           17.0   
이디야커피 신길역점              8.0       11.0          2.0            4.0   
엔제리너스 여의도리버타워점         51.0       43.0          7.0           37.0   

                "가성비가 좋아요"  "뷰가 좋아요"  "주차하기 편해요"  "사진이 잘 나와요"  \
search_name                                                     
버블베어                   0.0       0.0         1.0          0.0   
커피빈 낙성대역점              8.0      14.0         0.0          1.0   
노란꼬무줄 선릉본점            33.0       0.0         1.0          0.0   
커피랩                    4.0       5.0         0.0          4.0   
커핀그루나루 신천점             6.0       3.0         0.0          1.0   
빌리엔젤마리오아울렛            12.0       1.0        11.0          4.0   
할리스 남부터미널점            15.0       3.0         0.0          5.0   
홈스테드 타워팰리스점           18.0       1.0         0.0          0.0   
이

In [ ]:
naver_df.describe()

station_distance  total_review   "커피가 맛있어요"       "친절해요"   "음료가 맛있어요"  \
count       6878.000000   7661.000000  7661.000000  7661.000000  7661.000000   
mean         364.625182    217.937606    26.301658    25.684898    22.612453   
std          239.994461    340.399426    25.871534    22.441160    22.669105   
min            1.000000     10.000000     0.000000     0.000000     0.000000   
25%          174.000000     42.000000     6.000000     8.000000     6.000000   
50%          323.000000     93.000000    17.000000    19.000000    14.000000   
75%          526.000000    238.000000    41.000000    37.000000    32.000000   
max         1000.000000   6465.000000    99.000000    99.000000    99.000000   

       "디저트가 맛있어요"   "매장이 청결해요"   "대화하기 좋아요"   "집중하기 좋아요"  "인테리어가 멋져요"  \
count  7661.000000  7661.000000  7661.000000  7661.000000  7661.000000   
mean     19.629030    18.461036    13.598747     7.835922    14.579298   
std      21.725163    19.936589    18.261141    14.815950    18.890066   
min       0.000000     0.000000     0.000000     0.000000     0.000000   
25%       4.000000     5.000000     2.000000     1.000000     2.000000   
50%      11.000000    11.000000     6.000000     2.000000     7.000000   
75%      28.000000    25.000000    17.000000     7.000000    19.000000   
max      99.000000    99.000000    99.000000    99.000000    99.000000   

         "좌석이 편해요"  "화장실이 깨끗해요"  "특별한 메뉴가 있어요"   "가성비가 좋아요"     "뷰가 좋아요"  \
count  7661.000000  7661.000000    7661.000000  7661.000000  7661.000000   
mean      9.140974     5.409346      13.242788    14.862159     4.720402   
std      16.379410    10.994173      16.241039    18.196801    10.514301   
min       0.000000     0.000000       0.000000     0.000000     0.000000   
25%       1.000000     0.000000       3.000000     3.000000     0.000000   
50%       3.000000     1.000000       7.000000     8.000000     1.000000   
75%       9.000000     5.000000      17.000000    19.000000     4.000000   
max      99.000000    99.000000      98.000000    99.000000    96.000000   

        "주차하기 편해요"  "사진이 잘 나와요"  
count  7661.000000  7661.000000  
mean      3.046339     5.911108  
std       8.279852    10.318229  
min       0.000000     0.000000  
25%       0.000000     1.000000  
50%       0.000000     2.000000  
75%       2.000000     7.000000  
max      96.000000    99.000000

In [ ]:
naver_df.columns

Index(['address', 'road_address', 'near_station', 'station_distance',
       'total_review', '"커피가 맛있어요"', '"친절해요"', '"음료가 맛있어요"', '"디저트가 맛있어요"',
       '"매장이 청결해요"', '"대화하기 좋아요"', '"집중하기 좋아요"', '"인테리어가 멋져요"', '"좌석이 편해요"',
       '"화장실이 깨끗해요"', '"특별한 메뉴가 있어요"', '"가성비가 좋아요"', '"뷰가 좋아요"', '"주차하기 편해요"',
       '"사진이 잘 나와요"', 'cafe'],
      dtype='object')

### 카페 별 특징 파악

In [ ]:
# 카페 별 특징 수
num_attr = 15 - (naver_df[naver_df == 0].count(axis=1))
num_attr

search_name
버블베어             9
커피빈 낙성대역점       14
노란꼬무줄 선릉본점       9
커피랩             14
커핀그루나루 신천점      14
                ..
커피나무 보라매역점      14
스노잉 합정점         12
이디야커피 논골사거리점    15
퍼블릭맨션           12
이디야커피 굽은다리역점    12
Length: 7661, dtype: int64

In [ ]:
doc_freq = naver_df[naver_df != 0].count()
doc_freq

address             7661
road_address        6878
near_station        6878
station_distance    6878
total_review        7661
"커피가 맛있어요"          7161
"친절해요"              7558
"음료가 맛있어요"          7505
"디저트가 맛있어요"         7211
"매장이 청결해요"          7405
"대화하기 좋아요"          6924
"집중하기 좋아요"          5875
"인테리어가 멋져요"         6982
"좌석이 편해요"           5894
"화장실이 깨끗해요"         4951
"특별한 메뉴가 있어요"       7108
"가성비가 좋아요"          7217
"뷰가 좋아요"            4846
"주차하기 편해요"          3803
"사진이 잘 나와요"         5759
cafe                7661
dtype: int64

## 1. Binary

### 키워드 개수를 binary 값으로 변경

In [ ]:
naver = naver_df[['"커피가 맛있어요"', '"친절해요"',
       '"음료가 맛있어요"', '"디저트가 맛있어요"', '"매장이 청결해요"', '"대화하기 좋아요"', '"집중하기 좋아요"',
       '"인테리어가 멋져요"', '"좌석이 편해요"', '"화장실이 깨끗해요"', '"특별한 메뉴가 있어요"',
       '"가성비가 좋아요"', '"뷰가 좋아요"', '"주차하기 편해요"', '"사진이 잘 나와요"']]

In [ ]:
naver.head()

"커피가 맛있어요"  "친절해요"  "음료가 맛있어요"  "디저트가 맛있어요"  "매장이 청결해요"  \
search_name                                                            
버블베어                7.0     5.0         5.0          6.0         5.0   
커피빈 낙성대역점           7.0    56.0        74.0         37.0        40.0   
노란꼬무줄 선릉본점         40.0    14.0        61.0         39.0         2.0   
커피랩                76.0    23.0        13.0          9.0         8.0   
커핀그루나루 신천점         64.0    14.0        31.0         13.0        15.0   

             "대화하기 좋아요"  "집중하기 좋아요"  "인테리어가 멋져요"  "좌석이 편해요"  "화장실이 깨끗해요"  \
search_name                                                                
버블베어                0.0         0.0          0.0        1.0          2.0   
커피빈 낙성대역점          21.0        48.0          8.0       33.0          2.0   
노란꼬무줄 선릉본점          0.0         0.0          1.0        0.0          0.0   
커피랩                17.0        10.0         19.0        2.0          6.0   
커핀그루나루 신천점         29.0         7.0          2.0       15.0          5.0   

             "특별한 메뉴가 있어요"  "가성비가 좋아요"  "뷰가 좋아요"  "주차하기 편해요"  "사진이 잘 나와요"  
search_name                                                                
버블베어                   2.0         0.0       0.0         1.0          0.0  
커피빈 낙성대역점              2.0         8.0      14.0         0.0          1.0  
노란꼬무줄 선릉본점            21.0        33.0       0.0         1.0          0.0  
커피랩                   10.0         4.0       5.0         0.0          4.0  
커핀그루나루 신천점             5.0         6.0       3.0         0.0          1.0

In [ ]:
a = naver.astype(bool).astype(int)
a

"커피가 맛있어요"  "친절해요"  "음료가 맛있어요"  "디저트가 맛있어요"  "매장이 청결해요"  \
search_name                                                             
버블베어                   1       1           1            1           1   
커피빈 낙성대역점              1       1           1            1           1   
노란꼬무줄 선릉본점             1       1           1            1           1   
커피랩                    1       1           1            1           1   
커핀그루나루 신천점             1       1           1            1           1   
...                  ...     ...         ...          ...         ...   
커피나무 보라매역점             0       1           1            1           1   
스노잉 합정점                1       1           1            1           1   
이디야커피 논골사거리점           1       1           1            1           1   
퍼블릭맨션                  1       1           1            1           1   
이디야커피 굽은다리역점           1       1           1            1           1   

              "대화하기 좋아요"  "집중하기 좋아요"  "인테리어가 멋져요"  "좌석이 편해요"  "화장실이 깨끗해요"  \
search_name                                                                 
버블베어                   0           0            0          1            1   
커피빈 낙성대역점              1           1            1          1            1   
노란꼬무줄 선릉본점             0           0            1          0            0   
커피랩                    1           1            1          1            1   
커핀그루나루 신천점             1           1            1          1            1   
...                  ...         ...          ...        ...          ...   
커피나무 보라매역점             1           1            1          1            1   
스노잉 합정점                1           1            1          1            0   
이디야커피 논골사거리점           1           1            1          1            1   
퍼블릭맨션                  1           1            1          1            1   
이디야커피 굽은다리역점           1           1            1          0            0   

              "특별한 메뉴가 있어요"  "가성비가 좋아요"  "뷰가 좋아요"  "주차하기 편해요"  "사진이 잘 나와요"  
search_name                                                                 
버블베어                      1           0         0           1            0  
커피빈 낙성대역점                 1           1         1           0            1  
노란꼬무줄 선릉본점                1           1         0           1            0  
커피랩                       1           1         1           0            1  
커핀그루나루 신천점                1           1         1           0            1  
...                     ...         ...       ...         ...          ...  
커피나무 보라매역점                1           1         1           1            1  
스노잉 합정점                   1           1         0           0            1  
이디야커피 논골사거리점              1           1         1           1            1  
퍼블릭맨션                     1           1         0           0            0  
이디야커피 굽은다리역점              0           1         1           1            1  

[7661 rows x 15 columns]

### 카페 수와 카페 특징 수에 맞는 행렬 생성

In [ ]:
a.iloc[0].to_list()
list(a.iloc[0])

[1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0]

In [ ]:
score = np.zeros((7661, 15))
score.shape

for i in range(0,7661):
    score[i] = a.iloc[i].to_list()
    list(a.iloc[i])

In [ ]:
score[0]

array([1., 1., 1., 1., 1., 0., 0., 0., 1., 1., 1., 0., 0., 1., 0.])

In [ ]:
score[1]

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 1.])

In [ ]:
score[7660]

array([1., 1., 1., 1., 1., 1., 1., 1., 0., 0., 0., 1., 1., 1., 1.])

In [ ]:
print(score.shape, end='\n\n')
print(score)

(7661, 15)

[[1. 1. 1. ... 0. 1. 0.]
 [1. 1. 1. ... 1. 0. 1.]
 [1. 1. 1. ... 0. 1. 0.]
 ...
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 0. 0. 0.]
 [1. 1. 1. ... 1. 1. 1.]]


### 코사인 유사도 계산

In [ ]:
from sklearn.metrics.pairwise import cosine_similarity

In [ ]:
cosine_similar = cosine_similarity(score, score)

for i in range(7661):
    cosine_similar[i,i] = 1.0

cosine_similar_data = pd.DataFrame(cosine_similar,
                   index= naver_df['cafe'],
                   columns=naver_df['cafe'])
cosine_similar_data.head(10)

print(cosine_similar_data)

cafe                      버블베어 방화동  커피빈코리아낙성대역점 코리아낙성대역점 봉천동  노란고무줄 대치동  \
cafe                                                                      
버블베어 방화동                  1.000000                  0.712697   0.777778   
커피빈코리아낙성대역점 코리아낙성대역점 봉천동  0.712697                  1.000000   0.712697   
노란고무줄 대치동                 0.777778                  0.712697   1.000000   
커피랩 서교동                   0.712697                  1.000000   0.712697   
커핀그루나루신천점 신천점 잠실동         0.712697                  1.000000   0.712697   
...                            ...                       ...        ...   
커피나무 보라매역점 신길동            0.712697                  0.928571   0.712697   
스노잉합정점 합정점 합정동            0.673575                  0.925820   0.769800   
이디야커피 논골사거리점 금호동1가        0.774597                  0.966092   0.774597   
퍼블릭맨션 목동                  0.769800                  0.925820   0.769800   
이디야커피 굽은다리역점 천호동          0.577350                  0.848668   0.769800   

cafe                    

### 추천 함수 정의

In [ ]:
def content_recommender(name, n_of_recomm):
    # 주어진 카페와 다른 카페의 특징의 similarity를 가져온다
    sim_scores = cosine_similar_data[name]
    # similarity 기준으로 정렬하고 n_of_recomm만큼 가져오기 (자기자신은 빼기)
    sim_scores = sim_scores.sort_values(ascending=False)[1:n_of_recomm+1]
    # 비슷한 카페의 index number 반환
    return sim_scores

In [ ]:
print(content_recommender('버블베어 방화동', 5))

cafe
엘리스1871 1871 반포동    0.948683
목동빈스토리 목동           0.948683
카페 보스수유점 수유동        0.942809
백미당 잠실야구장점 잠실동      0.942809
설빙 롯데월드어드벤처점 잠실동    0.904534
Name: 버블베어 방화동, dtype: float64


#### 거리지표 추가

In [ ]:
public_df = pd.read_csv('C:\\Users\\jaewo\\Downloads\\publicdata_cafe_lastdrop.csv', index_col=0)

In [ ]:
public_df.head()

상호명          지점명 상권업종대분류코드 상권업종대분류명 상권업종중분류코드 상권업종중분류명 상권업종소분류코드  \
상가업소번호                                                                         
20659878    커피빈  코리아대학로대명거리점         Q       음식       Q12   커피점/카페    Q12A01   
20676428  요거프레소          쌍문점         Q       음식       Q12   커피점/카페    Q12A01   
28491095  우성커피숍          NaN         Q       음식       Q12   커피점/카페    Q12A01   
23260840   버블베어          NaN         Q       음식       Q12   커피점/카페    Q12A01   
22206830    알뤼르          NaN         Q       음식       Q12   커피점/카페    Q12A01   

             상권업종소분류명 표준산업분류코드   표준산업분류명  ...                도로명주소   구우편번호  \
상가업소번호                                    ...                                
20659878  커피전문점/카페/다방   I56220  비알콜 음료점업  ...     서울특별시 종로구 대명길 25  110524   
20676428  커피전문점/카페/다방   I56220  비알콜 음료점업  ...      서울특별시 도봉구 도당로 7  132030   
28491095  커피전문점/카페/다방   I56220  비알콜 음료점업  ...     서울특별시 양천구 오목로 48  158090   
23260840  커피전문점/카페/다방   I56220  비알콜 음료점업  ...   서울특별시 강서구 금낭화로 167  157788   
22206830  커피전문점/카페/다방   I56220  비알콜 음료점업  ...  서울특별시 강남구 삼성로85길 33  135280   

           신우편번호  동정보  층정보 호정보          경도         위도               이름  \
상가업소번호                                                                   
20659878  3078.0  NaN    3 NaN  127.000171  37.583149  커피빈 코리아대학로대명거리점   
20676428  1385.0  NaN    1 NaN  127.034746  37.658728        요거프레소 쌍문점   
28491095  8029.0  NaN    1 NaN  126.842935  37.522055            우성커피숍   
23260840  7509.0  NaN    1 NaN  126.813358  37.580941             버블베어   
22206830  6196.0  NaN  NaN NaN  127.054731  37.504378              알뤼르   

                          cafe  
상가업소번호                          
20659878  커피빈 코리아대학로대명거리점 명륜4가  
20676428         요거프레소 쌍문점 쌍문동  
28491095             우성커피숍 신월동  
23260840              버블베어 방화동  
22206830               알뤼르 대치동  

[5 rows x 40 columns]

In [ ]:
def content_recommender2(name, n_of_recomm, address):
    # 주어진 카페와 다른 카페의 특징의 similarity를 가져온다
    sim_scores = cosine_similar_data[name]
    # 비슷한 카페의 index number 반환
    sim_scores = sim_scores.sort_values(ascending=False)
    recom_cafe = pd.DataFrame(sim_scores, index=sim_scores.index)
    # 거리지표 추가
    recommendations = pd.merge(recom_cafe, public_df.set_index('cafe')[['시군구명','도로명주소']], left_index=True,right_index=True,how='left')
    # address 부분
    recommendations = recommendations[recommendations['시군구명']==address]
    R = recommendations.sort_values(by=[name], axis=0, ascending = False)[1:n_of_recomm+1]
    recommendations = R.iloc[:n_of_recomm,:]
    recommendations.columns = ['유사도','시군구명','도로명주소']
    return recommendations

In [ ]:
content_recommender2('메가커피 연희점 연희동', 3, '강남구')

유사도 시군구명                 도로명주소
cafe                                        
세이레스커피 삼성동    1.0  강남구  서울특별시 강남구 봉은사로68길 11
바오밥 나무커피 신사동  1.0  강남구  서울특별시 강남구 도산대로17길 10
TWG티 신사동      1.0  강남구     서울특별시 강남구 논현로 854

In [ ]:
content_recommender2('안다르커피 창천동', 10, '서대문구')

유사도  시군구명                   도로명주소
cafe                                                   
올바른커피 홍제동        0.881917  서대문구   서울특별시 서대문구 홍제내4길 4-11
커피베이 증가점 북가좌동    0.836660  서대문구      서울특별시 서대문구 증가로 262
셀렉토커피 가재울점 북가좌동  0.801784  서대문구  서울특별시 서대문구 수색로6길 17-14
데니스 커피명지대점 남가좌동  0.797724  서대문구     서울특별시 서대문구 명지대1라길 2
더벤티 서대문역점 냉천동    0.797724  서대문구      서울특별시 서대문구 통일로 147
잉겔스 창천동          0.797724  서대문구     서울특별시 서대문구 연희로2길 62
책다방위숨 창천동        0.771517  서대문구   서울특별시 서대문구 연세로9길 34-1
토굽스커피 연희동        0.771517  서대문구      서울특별시 서대문구 연희로 116
커피스튜디오 남가좌동      0.771517  서대문구   서울특별시 서대문구 모래내로15길 40
카페가가 충정로2가       0.763763  서대문구     서울특별시 서대문구 충정로 67-1

## 2. Vector

### 카페 수와 카페 특징 수에 맞는 행렬 생성

In [ ]:
naver.iloc[0].to_list()
list(naver.iloc[0])

[7.0, 5.0, 5.0, 6.0, 5.0, 0.0, 0.0, 0.0, 1.0, 2.0, 2.0, 0.0, 0.0, 1.0, 0.0]

In [ ]:
score = np.zeros((7661, 15))
score.shape

for i in range(0,7661):
    score[i] = naver.iloc[i].to_list()
    list(naver.iloc[i])

In [ ]:
score[0]

array([7., 5., 5., 6., 5., 0., 0., 0., 1., 2., 2., 0., 0., 1., 0.])

In [ ]:
score[1]

array([ 7., 56., 74., 37., 40., 21., 48.,  8., 33.,  2.,  2.,  8., 14.,
        0.,  1.])

In [ ]:
score[7660]

array([28., 20., 12.,  6., 11.,  8.,  3.,  3.,  0.,  0.,  0.,  3.,  1.,
        1.,  1.])

In [ ]:
print(score.shape, end='\n\n')
print(score)

(7661, 15)

[[ 7.  5.  5. ...  0.  1.  0.]
 [ 7. 56. 74. ... 14.  0.  1.]
 [40. 14. 61. ...  0.  1.  0.]
 ...
 [ 1. 46. 38. ...  2.  2.  6.]
 [17. 13.  9. ...  0.  0.  0.]
 [28. 20. 12. ...  1.  1.  1.]]


### 코사인 유사도 계산

In [ ]:
from sklearn.metrics.pairwise import cosine_similarity

In [ ]:
cosine_similar = cosine_similarity(score, score)

for i in range(7661):
    cosine_similar[i,i] = 1.0

cosine_similar_data = pd.DataFrame(cosine_similar,
                   index= naver_df['cafe'],
                   columns=naver_df['cafe'])
cosine_similar_data.head(10)

print(cosine_similar_data)

cafe                      버블베어 방화동  커피빈코리아낙성대역점 코리아낙성대역점 봉천동  노란고무줄 대치동  \
cafe                                                                      
버블베어 방화동                  1.000000                  0.709079   0.780252   
커피빈코리아낙성대역점 코리아낙성대역점 봉천동  0.709079                  1.000000   0.637136   
노란고무줄 대치동                 0.780252                  0.637136   1.000000   
커피랩 서교동                   0.740665                  0.423324   0.606264   
커핀그루나루신천점 신천점 잠실동         0.797174                  0.592999   0.715610   
...                            ...                       ...        ...   
커피나무 보라매역점 신길동            0.716295                  0.831546   0.633483   
스노잉합정점 합정점 합정동            0.814282                  0.667165   0.661421   
이디야커피 논골사거리점 금호동1가        0.628837                  0.910172   0.607047   
퍼블릭맨션 목동                  0.862588                  0.670667   0.685121   
이디야커피 굽은다리역점 천호동          0.864694                  0.648934   0.677004   

cafe                    

### 추천 함수 정의

In [ ]:
def content_recommender(name, n_of_recomm):
    # 주어진 카페와 다른 카페의 특징의 similarity를 가져온다
    sim_scores = cosine_similar_data[name]
    # similarity 기준으로 정렬하고 n_of_recomm만큼 가져오기 (자기자신은 빼기)
    sim_scores = sim_scores.sort_values(ascending=False)[1:n_of_recomm+1]
    # 비슷한 카페의 index number 반환
    return sim_scores

In [ ]:
print(content_recommender('버블베어 방화동', 5))

cafe
요거프레소 장지동점 장지동    0.964442
고호재롯데월드몰점 신천동     0.962879
지파시 연세암병원점 신촌동    0.959858
위드원스 신림동          0.959773
Cafe연 상월곡동        0.958861
Name: 버블베어 방화동, dtype: float64


In [ ]:
print(content_recommender('커피빈코리아낙성대역점 코리아낙성대역점 봉천동', 10))

cafe
커피빈코리아양천향교역점 코리아양천향교역점 마곡동       0.979125
커피빈 코리아선정릉역점 논현동                 0.977888
커피빈코리아천호역점 코리아천호역점 천호동           0.976183
메가커피 연희점 연희동                     0.967456
달콤 커피경희의료원점 회기동                  0.965690
커피빈 코리아서초뱅뱅사거리점 서초동              0.963089
탐앤탐스 신촌점 창천동                     0.960232
커피빈코리아외대앞점 코리아외대앞점 이문동           0.959526
커피빈코리아오목교역사거리점 코리아오목교역사거리점 목동    0.957656
커피빈 코리아구로지밸리몰점 구로동               0.955636
Name: 커피빈코리아낙성대역점 코리아낙성대역점 봉천동, dtype: float64


#### 거리지표 추가

In [ ]:
public_df = pd.read_csv('C:\\Users\\jaewo\\Downloads\\publicdata_cafe_lastdrop.csv', index_col=0)

In [ ]:
public_df.head()

상호명          지점명 상권업종대분류코드 상권업종대분류명 상권업종중분류코드 상권업종중분류명 상권업종소분류코드  \
상가업소번호                                                                         
20659878    커피빈  코리아대학로대명거리점         Q       음식       Q12   커피점/카페    Q12A01   
20676428  요거프레소          쌍문점         Q       음식       Q12   커피점/카페    Q12A01   
28491095  우성커피숍          NaN         Q       음식       Q12   커피점/카페    Q12A01   
23260840   버블베어          NaN         Q       음식       Q12   커피점/카페    Q12A01   
22206830    알뤼르          NaN         Q       음식       Q12   커피점/카페    Q12A01   

             상권업종소분류명 표준산업분류코드   표준산업분류명  ...                도로명주소   구우편번호  \
상가업소번호                                    ...                                
20659878  커피전문점/카페/다방   I56220  비알콜 음료점업  ...     서울특별시 종로구 대명길 25  110524   
20676428  커피전문점/카페/다방   I56220  비알콜 음료점업  ...      서울특별시 도봉구 도당로 7  132030   
28491095  커피전문점/카페/다방   I56220  비알콜 음료점업  ...     서울특별시 양천구 오목로 48  158090   
23260840  커피전문점/카페/다방   I56220  비알콜 음료점업  ...   서울특별시 강서구 금낭화로 167  157788   
22206830  커피전문점/카페/다방   I56220  비알콜 음료점업  ...  서울특별시 강남구 삼성로85길 33  135280   

           신우편번호  동정보  층정보 호정보          경도         위도               이름  \
상가업소번호                                                                   
20659878  3078.0  NaN    3 NaN  127.000171  37.583149  커피빈 코리아대학로대명거리점   
20676428  1385.0  NaN    1 NaN  127.034746  37.658728        요거프레소 쌍문점   
28491095  8029.0  NaN    1 NaN  126.842935  37.522055            우성커피숍   
23260840  7509.0  NaN    1 NaN  126.813358  37.580941             버블베어   
22206830  6196.0  NaN  NaN NaN  127.054731  37.504378              알뤼르   

                          cafe  
상가업소번호                          
20659878  커피빈 코리아대학로대명거리점 명륜4가  
20676428         요거프레소 쌍문점 쌍문동  
28491095             우성커피숍 신월동  
23260840              버블베어 방화동  
22206830               알뤼르 대치동  

[5 rows x 40 columns]

In [ ]:
def content_recommender2(name, n_of_recomm, address):
    # 주어진 카페와 다른 카페의 특징의 similarity를 가져온다
    sim_scores = cosine_similar_data[name]
    # 비슷한 카페의 index number 반환
    sim_scores = sim_scores.sort_values(ascending=False)
    recom_cafe = pd.DataFrame(sim_scores, index=sim_scores.index)
    # 거리지표 추가
    recommendations = pd.merge(recom_cafe, public_df.set_index('cafe')[['시군구명','도로명주소']], left_index=True,right_index=True,how='left')
    # address 부분
    recommendations = recommendations[recommendations['시군구명']==address]
    R = recommendations.sort_values(by=[name], axis=0, ascending = False)[1:n_of_recomm+1]
    recommendations = R.iloc[:n_of_recomm,:]
    recommendations.columns = ['유사도','시군구명','도로명주소']
    return recommendations

In [ ]:
content_recommender2('버블베어 방화동', 3, '서대문구')

유사도  시군구명                 도로명주소
cafe                                              
스플릿세컨드 연희동    0.956622  서대문구    서울특별시 서대문구 성산로 374
모두다가치카페 남가좌동  0.940890  서대문구  서울특별시 서대문구 명지대길 50-7
레이지나인 연희동     0.936910  서대문구   서울특별시 서대문구 연희로15길 5

In [ ]:
content_recommender2('안다르커피 창천동', 10, '서대문구')

유사도  시군구명                  도로명주소
cafe                                                      
카페필름포럼 대신동           0.887630  서대문구     서울특별시 서대문구 성산로 527
낙랑파라 아현점 북아현동        0.885633  서대문구   서울특별시 서대문구 신촌로31길 20
노아스로스팅 연희1호점 연희동     0.883055  서대문구  서울특별시 서대문구 연희로11가길 23
카페129-11 129-11 연희동  0.878022  서대문구  서울특별시 서대문구 연희로11가길 20
원오브씨 창천동             0.872068  서대문구     서울특별시 서대문구 신촌로3길 5
롱앤쇼트 홍제동             0.864608  서대문구   서울특별시 서대문구 홍제내2나길 46
카페문 대현동              0.861827  서대문구  서울특별시 서대문구 이화여대2가길 10
카페 제이미쉬 북가좌동         0.860601  서대문구     서울특별시 서대문구 수색로 102
스플릿세컨드 연희동           0.859067  서대문구     서울특별시 서대문구 성산로 374
산맥로스터리 북가좌동          0.857774  서대문구     서울특별시 서대문구 증가로 213